-- CREATE TABLE USERS (NAME VARCHAR(10) UNIQUE);

-- INSERT INTO USERS (NAME)
-- VALUES ('Carlos');

-- UPDATE USERS
-- SET NAME = 'Brayan'
-- WHERE NAME = 'Carlos';

-- SELECT *
-- FROM USERS
-- LIMIT 2
-- OFFSET 2 ;

-- SELECT *
-- FROM USERS
-- WHERE NAME LIKE '%Carlos%';

-- DELETE
-- FROM USERS
-- WHERE NAME LIKE '%Carlos%';

-- DELETE FROM USERS;

-- COMMIT;

-- ROLLBACK;
   
-- DROP TABLE USERS;

-- TRUNCATE TABLE USERS;

-- SELECT ID,
-- 	UPPER(NAME) AS UPPER_NAME,
-- 	LOWER(NAME) AS LOWER_NAME,
-- 	LENGTH(NAME) AS LENGTH,
-- 	(20 * 2) AS CONSTANTE,
-- 	'*' || ID || '-' || NAME || '*' AS BARCODE,
-- 	CONCAT('*',
-- 		ID,
-- 		'-',
-- 		NAME,
-- 		'*'),
-- 	NAME
-- FROM USERS;

-- SELECT NAME,
-- 	SUBSTRING(NAME,
-- 		0,
-- 		POSITION(' ' IN NAME)) AS FIRST_NAME,
-- 	SUBSTRING(NAME,
-- 		POSITION(' ' IN NAME) + 1) AS LAST_NAME,
-- 	TRIM(SUBSTRING(NAME,
-- 		POSITION(' ' IN NAME))) AS TRIMMED_LAST_NAME
-- FROM USERS;

-- UPDATE USERS
-- SET FIRST_NAME = SUBSTRING(NAME,0, POSITION(' ' IN NAME)),
-- 	LAST_NAME = SUBSTRING(NAME, POSITION(' ' IN NAME) + 1);




