-- SELECT FIRST_NAME,
-- 	LAST_NAME,
-- 	FOLLOWERS
-- FROM USERS
-- WHERE 
-- -- FOLLOWERS >= 4600 AND FOLLOWERS <= 4700
-- FOLLOWERS BETWEEN 4600 AND 4700
-- ORDER BY FOLLOWERS ASC;

-- SELECT FIRST_NAME,
-- 	LAST_NAME,
-- 	FOLLOWERS
-- FROM USERS
-- WHERE
-- -- FOLLOWERS >= 4600 AND FOLLOWERS <= 4700
-- FOLLOWERS BETWEEN 4600 AND 4700
-- ORDER BY FOLLOWERS ASC;
 -- SELECT COUNT(*) AS TOTAL_USERS,
-- 	MIN(FOLLOWERS) AS MIN_FOLLOWERS,
-- 	MAX(FOLLOWERS) AS MAX_FOLLOWERS,
-- 	ROUND(AVG(FOLLOWERS)) AS AVG_FOLLOWERS,
-- 	SUM(FOLLOWERS) / COUNT(*) AS AVG_MANUAL
-- FROM USERS;

-- SELECT FIRST_NAME,
-- 	LAST_NAME,
-- 	FOLLOWERS
-- FROM USERS
-- WHERE FOLLOWERS = 4
-- 	OR FOLLOWERS = 4999;

-- SELECT COUNT(*),
-- 	FOLLOWERS
-- FROM USERS
-- WHERE FOLLOWERS = 4
-- 	OR FOLLOWERS = 4999
-- GROUP BY FOLLOWERS;

-- SELECT COUNT(*),
-- 	FOLLOWERS
-- FROM USERS
-- WHERE FOLLOWERS BETWEEN 4500 AND 4999
-- GROUP BY FOLLOWERS
-- ORDER BY FOLLOWERS DESC;

-- SELECT COUNT(*) AS TOTAL,
-- 	COUNTRY
-- FROM USERS
-- GROUP BY COUNTRY
-- HAVING COUNT(*) BETWEEN 1 AND 5
-- ORDER BY COUNT(*) DESC;

-- SELECT DISTINCT COUNTRY
-- FROM USERS;

-- SELECT COUNT(*),
-- 	SUBSTRING(EMAIL, POSITION('@' IN EMAIL) + 1) AS DOMAIN
-- FROM USERS
-- GROUP BY SUBSTRING(EMAIL, POSITION('@' IN EMAIL) + 1)
-- HAVING COUNT(*) > 1
-- ORDER BY SUBSTRING(EMAIL, POSITION('@' IN EMAIL) + 1) ASC;

-- SELECT *
-- FROM
-- 	(SELECT COUNT(*) AS TOTAL,
-- 			SUBSTRING(EMAIL, POSITION('@' IN EMAIL) + 1) AS DOMAIN,
-- 			'Harold' AS NAME,
-- 			25 AS AGE
-- 		FROM USERS
-- 		GROUP BY SUBSTRING(EMAIL, POSITION('@' IN EMAIL) + 1)
-- 		HAVING COUNT(*) > 1
-- 		ORDER BY SUBSTRING(EMAIL, POSITION('@' IN EMAIL) + 1) ASC) AS EMAIL_DOMAINS;
